use tsql
go

CREATE TABLE CountryCurrency ([language] nvarchar(100), [langcode] nvarchar(20))
INSERT INTO CountryCurrency 
VALUES('Afrikaans - South Africa','af-ZA')
,('Albanian - Albania','sq-AL')
,('Alsatian - France','gsw-FR')
,('Amharic - Ethiopia','am-ET')
,('Arabic - Algeria','ar-DZ')
,('Arabic - Bahrain','ar-BH')
,('Arabic - Egypt','ar-EG')
,('Arabic - Iraq','ar-IQ')
,('Arabic - Jordan','ar-JO')
,('Arabic - Kuwait','ar-KW')
,('Arabic - Lebanon','ar-LB')
,('Arabic - Libya','ar-LY')
,('Arabic - Morocco','ar-MA')
,('Arabic - Oman','ar-OM')
,('Arabic - Qatar','ar-QA')
,('Arabic - Saudi Arabia','ar-SA')
,('Arabic - Syria','ar-SY')
,('Arabic - Tunisia','ar-TN')
,('Arabic - U.A.E.','ar-AE')
,('Arabic - Yemen','ar-YE')
,('Armenian - Armenia','hy-AM')
,('Assamese - India','as-IN')
,('Azerbaijani - Azerbaijan (Cyrillic)','az-Cyrl-AZ')
,('Azerbaijani - Azerbaijan (Latin)','az-Latn-AZ')
,('Bangla (Bangladesh)','bn-BD')
,('Bangla - India (Bengali Script)','bn-IN')
,('Bashkir - Russia','ba-RU')
,('Basque - Basque','eu-ES')
,('Belarusian - Belarus','be-BY')
,('Bosnian - Bosnia and Herzegovina (Cyrillic)','bs-Cyrl-BA')
,('Bosnian - Bosnia and Herzegovina (Latin)','bs-Latn-BA')
,('Breton - France','br-FR')
,('Bulgarian - Bulgaria','bg-BG')
,('Burmese - Myanmar','my-MM')
,('Catalan - Catalan','ca-ES')
,('Central Atlas Tamazight (Latin) - Algeria','fr-FR')
,('Central Atlas Tamazight (Latin) - Algeria','tzm-Latn-DZ')
,('Central Atlas Tamazight (Tifinagh) - Morocco','tzm-Tfng-MA')
,('Central Kurdish (Iraq)','ku-Arab-IQ')
,('Cherokee (Cherokee, United States)','chr-Cher-US')
,('Chinese (Simplified, China)','zh-CN')
,('Chinese - (Traditional, Taiwan)','zh-TW')
,('Corsican - France','co-FR')
,('Croatian - Bosnia and Herzegovina','hr-BA')
,('Croatian - Croatia','hr-HR')
,('Czech - Czech Republic','cs-CZ')
,('Danish - Denmark','da-DK')
,('Dari - Afghanistan','prs-AF')
,('Divehi - Maldives','dv-MV')
,('Dutch - Belgium','nl-BE')
,('Dutch - Netherlands','nl-NL')
,('Dzongkha','dz-BT')
,('English - Australia','en-AU')
,('English - Belize','en-BZ')
,('English - Canada','en-CA')
,('English - Caribbean','en-029')
,('English - India','en-IN')
,('English - Ireland','en-IE')
,('English - Jamaica','en-JM')
,('English - Malaysia','en-MY')
,('English - New Zealand','en-NZ')
,('English - Philippines','en-PH')
,('English - Singapore','en-SG')
,('English - South Africa','en-ZA')
,('English - Trinidad','en-TT')
,('English - Great Britain','en-GB')
,('English - United States','en-US')
,('English - Zimbabwe','en-ZW')
,('Estonian - Estonia','et-EE')
,('Faroese - Faroe Islands','fo-FO')
,('Filipino - Philippines','fil-PH')
,('Finnish - Finland','fi-FI')
,('French - Belgium','fr-BE')
,('French - Canada','fr-CA')
,('French - France','fr-FR')
,('French - Luxembourg','fr-LU')
,('French - Monaco','fr-MC')
,('French - Switzerland','fr-CH')
,('Frisian - Netherlands','fy-NL')
,('Fulah (Latin, Senegal)','ff-Latn-SN')
,('Galician - Galician','gl-ES')
,('Georgian - Georgia','ka-GE')
,('German - Austria','de-AT')
,('German - Germany','de-DE')
,('German - Liechtenstein','de-LI')
,('German - Luxembourg','de-LU')
,('German - Switzerland','de-CH')
,('Greek - Greece','el-GR')
,('Greenlandic - Greenland','kl-GL')
,('Guarani - Paraguay','gn-PY')
,('Gujarati - India (Gujarati Script)','gu-IN')
,('Hausa (Latin) - Nigeria','ha-Latn-NG')
,('Hawaiian - United States','haw-US')
,('Hebrew - Israel','he-IL')
,('Hindi - India','hi-IN')
,('Hungarian - Hungary','hu-HU')
,('Icelandic - Iceland','is-IS')
,('Igbo - Nigeria','ig-NG')
,('Inari Sami - Finland','smn-FI')
,('Indonesian - Indonesia','id-ID')
,('Inuktitut (Latin) - Canada','iu-Latn-CA')
,('Inuktitut (Syllabics) - Canada','iu-Cans-CA')
,('Irish - Ireland','ga-IE')
,('isiXhosa / Xhosa - South Africa','xh-ZA')
,('isiZulu / Zulu - South Africa','zu-ZA')
,('Italian - Italy','it-IT')
,('Italian - Switzerland','it-CH')
,('Japanese - Japan','ja-JP')
,('Javanese (Latin) - Indonesia','jv-Latn-ID')
,('Kannada - India (Kannada Script)','kn-IN')
,('Kazakh - Kazakhstan','kk-KZ')
,('Khmer - Cambodia','km-KH')
,('Kiche - Guatemala','qut-GT')
,('Kinyarwanda - Rwanda','rw-RW')
,('Konkani - India','kok-IN')
,('Korean(Extended Wansung) - Korea','ko-KR')
,('Kyrgyz - Kyrgyzstan','ky-KG')
,('Lao - Lao PDR','lo-LA')
,('Latvian - Legacy','lv-LV')
,('Latvian - Standard','lv-LV')
,('Lithuanian - Lithuania','lt-LT')
,('Lower Sorbian - Germany','dsb-DE')
,('Lule Sami - Norway','smj-NO')
,('Lule Sami - Sweden','smj-SE')
,('Luxembourgish - Luxembourg','lb-LU')
,('Macedonian - F.Y.R.O.M','mk-MK')
,('Malay - Brunei','ms-BN')
,('Malay - Malaysia','ms-MY')
,('Malayalam - India (Malayalam Script)','ml-IN')
,('Maltese - Malta','mt-MT')
,('Maori - New Zealand','mi-NZ')
,('Mapudungun - Chile','arn-CL')
,('Marathi - India','mr-IN')
,('Mohawk - Mohawk','moh-CA')
,('Mongolian (Cyrillic) - Mongolia','mn-MN')
,('Mongolian (Mongolian) - Mongolia','mn-Mong-MN')
,('Mongolian (Traditional Mongolian - China - Legacy)','mn-Mong-CN')
,('Mongolian (Traditional Mongolian - China - Standard)','mn-Mong-CN')
,('Nko - Guinea','nqo-GN')
,('Nepali - Federal Democratic Republic of Nepal','ne-NP')
,('Northern Sami - Finland','se-FI')
,('Northern Sami - Norway','se-NO')
,('Northern Sami - Sweden','se-SE')
,('Norwegian - Norway (Bokmål)','nb-NO')
,('Norwegian - Norway (Nynorsk)','nn-NO')
,('Occitan - France','oc-FR')
,('Odia - India (Odia Script)','or-IN')
,('Pashto - Afghanistan','ps-AF')
,('Persian','fa-IR')
,('Polish - Poland','pl-PL')
,('Portuguese - Brazil','pt-BR')
,('Portuguese - Portugal','pt-PT')
,('Punjabi - India (Gurmukhi Script)','pa-IN')
,('Punjabi (Islamic Republic of Pakistan)','pa-Arab-PK')
,('Quechua - Bolivia','quz-BO')
,('Quechua - Ecuador','quz-EC')
,('Quechua - Peru','quz-PE')
,('Romanian - Romania','ro-RO')
,('Romansh - Switzerland','rm-CH')
,('Russian - Russia','ru-RU')
,('Sakha - Russia','sah-RU')
,('Sanskrit - India','sa-IN')
,('Scottish Gaelic - Great Britain','gd-GB')
,('Serbian - Bosnia and Herzegovina (Cyrillic)','sr-Cyrl-BA')
,('Serbian - Bosnia and Herzegovina (Latin)','sr-Latn-BA')
,('Serbian - Montenegro (Cyrillic)','sr-Cyrl-ME')
,('Serbian - Montenegro (Latin)','sr-Latn-ME')
,('Serbian - Serbia (Cyrillic)','sr-Cyrl-RS')
,('Serbian - Serbia (Latin)','sr-Latn-RS')
,('Serbian - Serbia and Montenegro (Former) (Cyrillic)','sr-Cyrl-CS')
,('Serbian - Serbia and Montenegro (Former) (Latin)','sr-Latn-CS')
,('Sesotho sa Leboa / Northern Sotho - South Africa','nso-ZA')
,('Setswana / Tswana - Botswana','tn-BW')
,('Setswana / Tswana - South Africa','tn-ZA')
,('Shona - Zimbabwe','sn-Latn-ZW')
,('Sindhi (Islamic Republic of Pakistan)','sd-Arab-PK')
,('Sinhala - Sri Lanka','si-LK')
,('Skolt Sami - Finland','sms-FI')
,('Slovak - Slovakia','sk-SK')
,('Slovenian - Slovenia','sl-SI')
,('Southern Sami - Norway','sma-NO')
,('Southern Sami - Sweden','sma-SE')
,('Spanish - Argentina','es-AR')
,('Spanish - Bolivarian Republic of Venezuela','es-VE')
,('Spanish - Bolivia','es-BO')
,('Spanish - Chile','es-CL')
,('Spanish - Colombia','es-CO')
,('Spanish - Costa Rica','es-CR')
,('Spanish - Dominican Republic','es-DO')
,('Spanish - Ecuador','es-EC')
,('Spanish - El Salvador','es-SV')
,('Spanish - Guatemala','es-GT')
,('Spanish - Honduras','es-HN')
,('Spanish - Latin America','es-419')
,('Spanish - Mexico','es-MX')
,('Spanish - Nicaragua','es-NI')
,('Spanish - Panama','es-PA')
,('Spanish - Paraguay','es-PY')
,('Spanish - Peru','es-PE')
,('Spanish - Commonwealth of Puerto Rico','es-PR')
,('Spanish - Spain (International Sort)','es-ES')
,('Spanish - Spain (Traditional Sort)','es-ES_tradnl')
,('Spanish - United States','es-US')
,('Spanish - Uruguay','es-UY')
,('Standard Moroccan Tamazight - Morocco','zgh-Tfng-MA')
,('Swahili - Kenya','sw-KE')
,('Swedish - Finland','sv-FI')
,('Swedish - Sweden','sv-SE')
,('Syriac - Syria','syr-SY')
,('Tajik - Tajikistan','tg-Cyrl-TJ')
,('Tamil - India','ta-IN')
,('Tamil - Sri Lanka','ta-LK')
,('Tatar - Russia (Legacy)','tt-RU')
,('Tatar - Russia (Standard)','tt-RU')
,('Telugu - India (Telugu Script)','te-IN')
,('Thai - Thailand','th-TH')
,('Tibetan - China','bo-CN')
,('Tigrinya (Eritrea)','ti-ET')
,('Tigrinya (Ethiopia)','ti-ET')
,('Turkish - Turkey','tr-TR')
,('Turkmen - Turkmenistan','tk-TM')
,('Ukrainian - Ukraine','uk-UA')
,('Upper Sorbian - Germany','hsb-DE')
,('Urdu - India','ur-IN')
,('Urdu (Islamic Republic of Pakistan)','ur-PK')
,('Uyghur - China','ug-CN')
,('Uzbek - Uzbekistan (Cyrillic)','uz-Cyrl-UZ')
,('Uzbek - Uzbekistan (Latin)','uz-Latn-UZ')
,('Valencian - Valencia','ca-ES-valencia')
,('Vietnamese - Vietnam','vi-VN')
,('Welsh - Great Britain','cy-GB')
,('Wolof - Senegal','wo-SN')
,('Yi - China','ii-CN')
 
